GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub3RoZXJkYXkiLCJpZCI6IjYxNWM5MmM4NzQ1MGJkY2Q0Y2ZjZDdkNSIsImlhdCI6MTYzMzQ1Njk3OCwiZXhwIjoxNjMzNDYwNTc4fQ.gRmjyEgQz1Qsfixg6xNBUVrsybEelv941gF_jwX-Q8c

{
  "title": "Going to the Driving Range",
  "author": "More Stuff",
  "url": "http://www.golf.com",
  "likes": 163,
  "userId": "615b3a81b8d4b980b6401359"
}

###
DELETE http://localhost:3003/api/blogs/615c93647450bdcd4cfcd7db
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXJ0aW1lIiwiaWQiOiI2MTVjOTY2YjE0NTMyYzk1MDI5M2Q1NDciLCJpYXQiOjE2MzM0NTc3ODksImV4cCI6MTYzMzQ2MTM4OX0.ivxjvi5RVmw7EMxJofZL_V2zavolZG1NDWhfB57m7RM

###
GET http://localhost:3003/api/blogs/615c93647450bdcd4cfcd7db
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub3RoZXJkYXkiLCJpZCI6IjYxNWM5MmM4NzQ1MGJkY2Q0Y2ZjZDdkNSIsImlhdCI6MTYzMzQ1Njk3OCwiZXhwIjoxNjMzNDYwNTc4fQ.gRmjyEgQz1Qsfixg6xNBUVrsybEelv941gF_jwX-Q8c

###
PUT  http://localhost:3003/api/blogs/615b389aa84143492c07c2e0 
content-type: application/json

{
    "likes": 2654
}

###
GET http://localhost:3003/api/users/ 

###
POST http://localhost:3003/api/users/ 
content-type: application/json

{
    "username": "newusertime",
    "name": "swole",
    "password": "darkness33"
}
