GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdzZmdzZmdzZGciLCJpZCI6IjYxNWIzYTgxYjhkNGI5ODBiNjQwMTM1OSIsImlhdCI6MTYzMzM3ODM3MiwiZXhwIjoxNjMzMzgxOTcyfQ.6vNAVy3G-LNb4QRBQ1H63SS1k2Hyd3TXNGY746tpQw0

{
  "title": "Going to the Driving Range",
  "author": "More Stuff",
  "url": "http://www.golf.com",
  "likes": 163,
  "userId": "615b3a81b8d4b980b6401359"
}

###
DELETE http://localhost:3003/api/blogs/6159e568e05f480b8ae503a2

###
PUT  http://localhost:3003/api/blogs/615b389aa84143492c07c2e0 
content-type: application/json

{
    "likes": 2654
}

###
GET http://localhost:3003/api/users/ 

###
POST http://localhost:3003/api/users/ 
content-type: application/json

{
    "username": "gsfgsfgsdg",
    "name": "panama",
    "password": "jhsdfsfsds"
}
